### ISSUE TITLE
this.options.authnContext.forEach is not a function

### ISSUE THREAD

**Issue by smclinden** [LuatixHQ/opencti#2791]
## Description

Using SAML I get the error above. This was after an upgrade to the latest release.

## Environment

1. OS: Ubuntu 20.04
2. OpenCTI version: 5.5.2 (from 5.4.1)
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Upgraded from 5.4.1 to 5.5.2
2. No changes to configuration
3. When I try to login using SAML (which used to work) I get the above.

## Expected Output

Normal login

## Actual Output

See above

**Comment by smclinden** [comment]
Ok, found a "partial" solution.

If I add the following to the SAML connector config, I get to the Microsoft Login (the Authn error goes away) but the callback no longer works.
```
"disableRequestedAuthnContext": true,
```

Please check the following for configuring SAML for Active Directory.

https://github.com/node-saml/passport-saml

**Comment by richard-julien** [comment]
Hi @smclinden ,

Do you use the configuration of the authnContext option?

If yes looks like using a string is no longer supported by the passport lib (https://github.com/node-saml/passport-saml/issues/681)

If yes you need to replace your string configuration by an array.

Can you put here your anonymised saml configuration ?

Thanks

**Comment by smclinden** [comment]
The following worked, without the disableRequestedAuthnContext option until the latest version of OpenCTI.
```
 "providers": {
    "saml": {
        "identifier": "saml",
        "strategy": "SamlStrategy",
        "config": {
            "issuer": "opencti",
            "entry_point": "https://login.microsoftonline.com/{uid}/saml2",
            "saml_callack_url": "https://opencti.xxx.com:4000/auth/saml/callback",
            "authnContext": "https://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows",
            "callback_url": "https://opencti.xxx.com:4000/saml/consume",
            "identifierFormat": null,
            "disableRequestedAuthnContext": true,
            "cert": "MII......A3r",
            "roles_management": {
              "role_attributes": ["Role"],
              "roles_mapping": ["ITSecOps"]
            }
        }
    },
```

Now I get the following:

```
AADSTS50011: The reply URL 'http://opencti.xxx.com:4000/saml/consume' specified 
in the request does not match the reply URLs configured for the application 'opencti'. 
Make sure the reply URL sent in the request matches one
added to your application in the Azure portal. Navigate to https://aka.ms/urlMismatchError 
to learn more about how to fix this. 
```

**Comment by richard-julien** [comment]
can you try this kind of configuration?

```
 "providers": {
    "saml": {
        "identifier": "saml",
        "strategy": "SamlStrategy",
        "config": {
            "issuer": "opencti",
            "entry_point": "https://login.microsoftonline.com/{uid}/saml2",
            "saml_callback_url": "https://opencti.xxx.com:4000/auth/saml/callback",
            "authnContext": ["https://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows"],
            "identifierFormat": null,
            "cert": "MII......A3r",
            "roles_management": {
              "role_attributes": ["Role"],
              "roles_mapping": ["ITSecOps"]
            }
        }
    },
```

**Comment by smclinden** [comment]
```
Sorry, but we’re having trouble signing you in.

AADSTS50130: The claim value(s) 'https://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows' cannot be interpreted as known auth method(s).
```

**Comment by smclinden** [comment]
According to the passport-saml documentation it is expecting an array of objects of the form

__urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport__

**Comment by smclinden** [comment]
Ok, so I am confused. The passport-saml GitHub states that the callback path should be **/saml/consume** but your example documentation states that it should be **/auth/saml/consume**. I tried switching these in AD and the config and in ALL cases, it claims that the callback URL does not match the URL configured in the application.

That, simply, isn't true so it must be something else.

My suspicion is that the callbackURL is not being created by OpenCTI so no matter what the value in AD, it can't be found in OpenCTI.

**Comment by g7eg10r** [comment]
> The following worked, without the disableRequestedAuthnContext option until the latest version of OpenCTI.
> 
> ```
>  "providers": {
>     "saml": {
>         "identifier": "saml",
>         "strategy": "SamlStrategy",
>         "config": {
>             "issuer": "opencti",
>             "entry_point": "https://login.microsoftonline.com/{uid}/saml2",
>             "saml_callack_url": "https://opencti.xxx.com:4000/auth/saml/callback",
>             "authnContext": "https://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows",
>             "callback_url": "https://opencti.xxx.com:4000/saml/consume",
>             "identifierFormat": null,
>             "disableRequestedAuthnContext": true,
>             "cert": "MII......A3r",
>             "roles_management": {
>               "role_attributes": ["Role"],
>               "roles_mapping": ["ITSecOps"]
>             }
>         }
>     },
> ```
> 
> Now I get the following:
> 
> ```
> AADSTS50011: The reply URL 'http://opencti.xxx.com:4000/saml/consume' specified 
> in the request does not match the reply URLs configured for the application 'opencti'. 
> Make sure the reply URL sent in the request matches one
> added to your application in the Azure portal. Navigate to https://aka.ms/urlMismatchError 
> to learn more about how to fix this. 
> ```

Hi, I was just wandering through this issue report and just noticed a few points (I've no clue if it will help solving the issue):

1. there is a typo in the pasted configuration (`saml_callack_url` instead of `saml_callback_url`) ; is the field name correct in your effective configuration (the one used by OpenCTI)?
2. there is a difference in the protocol indicated in your configuration (`https`) and the one in the error message (plain `http`). Could there be some discrepancy between what's configured on both sides (OpenCTI and Azure)? Or is it possible that given the typo above, the redirect URL provided by OpenCTI to Azure is not the correct one?

**Comment by smclinden** [comment]
There is s typographical error in the pasted configuration, above. The production version is correct. And I have checked in Azure and this is the callback URL in the Azure configuration, as well.

OpenCTI is running in secure mode so all traffic to it should be HTTPS unless I am misunderstanding.

Thank you for looking.

**Comment by smclinden** [comment]
Ok, latest installment. When I run the test from Azure, I have no problems with SAML authentication. When I try to access the site using a browser, I get: **Cannot POST /saml/consume** (yes, I changed the URL to match the default for passport-saml).

I did a curl from a shell on the OpenCTI server and I get the following:

```
# curl -v https://opencti.xxxx.com:4000/saml/consume
*   Trying 10.223.130.132:4000...
* TCP_NODELAY set
* Connected to opencti.xxxx.com (10.223.130.132) port 4000 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=xxxx; L=xxxx; O=xxxx; OU=xxxx; CN=opencti.xxxx.com
*  start date: Aug 15 12:56:06 2022 GMT
*  expire date: Sep 17 12:56:06 2023 GMT
*  subjectAltName: host "opencti.xxxx.com" matched cert's "opencti.xxxx.com"
*  issuer: C=US; DC=xxxx; DC=xxxx; ST=xxxx; L=xxxx; O=xxxx; CN=xxxx
*  SSL certificate verify ok.
> GET /saml/consume HTTP/1.1
> Host: opencti.xxxx.com:4000
> User-Agent: curl/7.68.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-RateLimit-Limit: 10000
< X-RateLimit-Remaining: 9999
< Date: Thu, 02 Feb 2023 18:28:00 GMT
< X-RateLimit-Reset: 1675362481
< Content-Security-Policy: default-src 'self';script-src 'self' 'unsafe-inline' http://cdn.jsdelivr.net/npm/@apollographql/;style-src 'self' 'unsafe-inline' http://cdn.jsdelivr.net/npm/@apollographql/ https://fonts.googleapis.com/;script-src-attr 'self' 'unsafe-inline' http://cdn.jsdelivr.net/npm/@apollographql/ https://fonts.googleapis.com/;font-src 'self' data: https://fonts.gstatic.com/;img-src 'self' data: https://* http://*;connect-src 'self' wss://* ws://* data: http://* https://*;object-src 'self' data: http://* https://*;frame-src 'self' data: http://* https://*
< X-DNS-Prefetch-Control: off
< Expect-CT: max-age=30, enforce
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< X-Download-Options: noopen
< X-Content-Type-Options: nosniff
< Origin-Agent-Cluster: ?1
< X-Permitted-Cross-Domain-Policies: none
< Referrer-Policy: unsafe-url
< X-XSS-Protection: 0
< Cache-Control: private, no-cache, no-store, must-revalidate
< Expires: -1
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Content-Length: 1067
< ETag: W/"42b-C7nK3LnLh2RtXhHx+OdVNfO4T4o"
< Vary: Accept-Encoding
< Connection: keep-alive
< Keep-Alive: timeout=5
<

    <!doctype html>
    <html lang="en">
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width,initial-scale=1">
            <meta name="dеѕсrірtіоn" content="xxxx is an open source platform allowing organizations to manage their cyber threat intelligence knowledge and observables.">
            <link id="favicon" rel="shortcut icon" href="/static/ext/favicon.png">
            <link id="manifest" rel="manifest" href="/static/ext/manifest.json">
            <script>window.BASE_PATH = ""</script>
            <script defer="defer" src="/static/js/front-SCNPRCGI.js"></script>
            <link href="/static/css/front-4UPNVIC6.css" rel="stylesheet">
            <title>Cyber threat intelligence platform</title>
        </head>
        <body>
            <noscript>You need to enable JavaScript to run this app.</noscript>
            <div id="root"></div>
        </body>
* Connection #0 to host opencti.xxxx.com left intact
```

**Comment by richard-julien** [comment]
/saml/consume is  not a valib callback uri for opencti.

The valid configuration should be

`"saml_callback_url": "https://opencti.xxx.com:4000/auth/saml/callback",`

**Comment by smclinden** [comment]
I'm trying to understand where this is in the code and why the default for passport-saml is not used.

Also, I used the default, above, and got the error that I posted, originally.

**Comment by smclinden** [comment]
I guess my point is that I updated to the latest release without changing anything (except upgrading to the latest dependencies) and that broke SAML and I am trying to understand why?

**Comment by richard-julien** [comment]
The default is not used because we need to adapt the authentication to our own needs.
Sometimes stuff break because on every release we also upgrade our dependencies. The SAML lib was upgraded in the latest release. The only thing we can see for now its that new release of the SAML lib change the authnContext to be a list instead of a string. Maybe there is also some other changes but its very difficult to help you without a repro case. Do you think it could be possible for you to give us a repro case environment?

Thanks

**Comment by smclinden** [comment]
The last release that I was running before the current was 5.3.17 which used passport-saml 3.2.1. Everything ran fine.

The current release of OpenCTI uses 3.2.4 (passport-saml has been deprecated and the newest versions are @node-saml/passport-saml).

If I make this: 

```
"authnContext": "https://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows", 

```
a list instead of a string it gives me an error:

```
Sorry, but we’re having trouble signing you in.

AADSTS50130: The claim value(s) 'https://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows' cannot be interpreted as known auth method(s).
```

If I omit it altogether it defaults to:

```
urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport

```
If I use the suggested configuration, it gives me an error:

```
Invalid authentication, please ask your administrator
```

Except that I am the administrator and I made no other changes since the last release and reverted to the **saml_callback_url** that your instructions specified,

**Comment by smclinden** [comment]
Just as an FYI, the Azure log files show that the authentication was successful so this has something to do with post authentication logic.

**Comment by srd90** [comment]
This issue is "leaking" to multiple repositories (see https://github.com/node-saml/passport-saml/issues/847) and it seems that even in this "home repository" this issue is spinning to multiple issues.

As far as I can tell issue description said at the very beginning:
>Using SAML I get the error above. This was after an upgrade to the latest release.
>...
>Environment
>...
>2. OpenCTI version: 5.5.2 (from 5.4.1)
>
>...
>Reproducible Steps
>...
>3. When I try to login using SAML (which used to work) I get the above.

And as far as I can interpret "I get the error above" means title of issue:
>this.options.authnContext.forEach is not a function

Lets see which versions of `passport-saml` OpenCTI 5.4.1 and 5.5.2 used:
* 5.4.1:
  https://github.com/OpenCTI-Platform/opencti/blob/51c2ea90933804cdda874844cc888261d2e13510/opencti-platform/opencti-graphql/package.json#L111
* 5.5.2:
  https://github.com/OpenCTI-Platform/opencti/blob/19d160ea07d3409593a03f1b79e546cdfc3f7c03/opencti-platform/opencti-graphql/package.json#L111

Issue description implicates that configuration was same and things started to fail (with "options.authnContext.forEach is not a function") after upgrade from 5.4.1 --> 5.5.2.

`passport-saml` version was 3.2.4 in both OpenCTI versions and line which failed looks like this (refers to version 3.2.4):
https://github.com/node-saml/passport-saml/blob/v3.2.4/src/node-saml/saml.ts#L281

---

Later in this issue (see https://github.com/OpenCTI-Platform/opencti/issues/2791#issuecomment-1417944886) it is said that
>The last release that I was running before the current was 5.3.17 which used passport-saml 3.2.1. Everything ran fine.

(which is not what issue description said about version)

OpenCTI 5.3.17 indeed uses passport-saml 3.2.1
https://github.com/OpenCTI-Platform/opencti/blob/70d2c413ed0ff57f779acd92866672a810977d3d/opencti-platform/opencti-graphql/package.json#L93

BUT passport-saml 3.2.1 expected also `authnContext` to be array (it does not convert provided authnContext string to array of string(s) anymore like e.g. v2.2.0 did ... see later on this message)
https://github.com/node-saml/passport-saml/blob/v3.2.1/src/node-saml/saml.ts#L281

---

So if issue ("authnContext.forEach is not a function") occurred after OpenCTI upgrade from `5.3.17 / 5.4.1` ---> `5.5.2` and if configuration was same as before then I just wonder how that is possible.

If authnContext was NOT array of strings and OpenCTI worked with that configuratino then it means that there must have been version of `passport-saml` which accepted also string as value of authnContext.

Last `passport-saml` version which accepted one string as value of `authnContext` was prior this PR https://github.com/node-saml/passport-saml/pull/548/ was merged.

I.e. last `passport-saml` version which supported authnContext with plain string was 2.2.0 (and that version supported string so that it was implicitly modified to array of string(s)): https://github.com/node-saml/passport-saml/blob/v2.2.0/src/passport-saml/saml.ts#L165-L167

I.e. if you had configuration which had `"authnContext": "....blabla..."` and it did not cause "forEach is not a function" error then you must have been using passport-saml `< 3.0.0` version.

Last version of OpenCTI which uses passport-saml < 3.0.0 was OpenCTI 4.5.4 (link refers to that version's package.json):
https://github.com/OpenCTI-Platform/opencti/blob/bba9a18dcf842183076d85d6449f1a498ec0878b/opencti-platform/opencti-graphql/package.json#L84

---

Random side notes:
You seems to be wondering where in the OpenCTI codebase `/auth/...` endoint is located

@richard-julien wrote:
>/saml/consume is not a valib callback uri for opencti.
>
>The valid configuration should be
>
>`"saml_callback_url": "https://opencti.xxx.com:4000/auth/saml/callback",`

@smclinden you asked
>I'm trying to understand where this is in the code and why the default for passport-saml is not used.
>...

souce: https://github.com/OpenCTI-Platform/opencti/issues/2791#issuecomment-1416494351

`/auth/saml/callback` handler seems to be here (link refers to OpenCTI 5.5.2 version):
https://github.com/OpenCTI-Platform/opencti/blob/904f7d5155ae9a453cc5716039d4c162b0006bf1/opencti-platform/opencti-graphql/src/http/httpPlatform.js#L241-L265

**Comment by richard-julien** [comment]
@smclinden 

```
If I use the suggested configuration, it gives me an error:

Invalid authentication, please ask your administrator
Except that I am the administrator and I made no other changes since the last release and reverted to the saml_callback_url that your instructions specified,
```

If you get this error you should have an error log in your api "LOGIN" with more information about the problem.

As i said in my previous message, debugging your auth integration problem without direct discussion and a repro environment will be extremely complex.

**Comment by smclinden** [comment]
A repro environment when we have gone through 5 upgrades of OpenCTI, an upgrade of Ubuntu from 18.04 to 20.04, updates (mandated by the dependency requirements) to Minio, Elasticsearch, Node, passport, etc., and the last one breaks authentication...?

Let me ask you this. Are the latest release instructions part of a rolling upgrade or a fresh install?

Because I don't have the luxury of clean installs. Not when every dependency changes!

**Comment by richard-julien** [comment]
I just try to help you as much as I can...

We have a lot of users included ourself (opencti demo use SAML authentication through azure) that have no problem at all. 

When i talk repro case env i talk about only the SAML part where you can maybe replicate the azure SAML configuration somewhere to expose us the auth service. With that we will be able to try the login ourself and find the problem. We are ready to sign any NDA or other document if we need to.

**Comment by smclinden** [comment]
Believe me, I understand. You have helped me with migrations, before and I appreciate that!

But all of this is behind a firewall so what you ask would be hard to do.

What can I look for in the OpenCTI logs that I can send you?

Azure says that the authentication succeeded, but the Web front end says otherwise.  I'm trying to understand why? 

Unfortunately, the Azure analyzer log of the authentication never returns.

I can send the log data that I have from Azure, if that would help?

**Comment by richard-julien** [comment]
We can try. \you can send the azure logs + opencti logs during a fail auth.

**Comment by srd90** [comment]
One more side note:
Consider asking from @smclinden  / sharing to @richard-julien also decoded SAML protocol level message traces which shows what is being signaled back and forth via front channel communication mechanism and which (contents of the SAML messages) reflect/expose quite alot of effective configuration being used at both ends of communication channel.

E.g.: SAML tracer browser plugin provides capabilities to save such traces:  https://chrome.google.com/webstore/detail/saml-tracer/mpdajninpobndbfcldcmbpnnbhibjmch?hl=en

**Comment by smclinden** [comment]
I'm afraid that the logs arent very helpful.

```
{"auth":{"ip":"172.31.91.166","referer":"https://login.microsoftonline.com/"},"category":"AUDIT","level":"error","message":"LOGIN","resource":{"error":"Restricted access, ask your administrator","provider":"saml"},"timestamp":"2023-02-06T14:34:48.310Z","version":"5.5.2"}
```

This comes from src/config/provider.js and it looks like the call to providerLoginHandler has changed since the prior working release. But  the Azure logs say this:

```

2/6/2023 9:34:23 AM a5c95025-xxxx-xxxx-xxxx-efa34a0eca00 Mclinden, Sean OpenCTI Success nnn.nn.nnn.nn City State, US Success No Single-factor authentication

```
The "No" means that the event was not flagged. 

So the difference is in the way that providerLoginHandler is being used.

**Comment by richard-julien** [comment]
In fact it is interesting @smclinden . This error occured if the login is successful but the platform is not able to assign the correct roles or groups after authentication.
Can you restart your platform in debug and retry a login ?
In debug mode you will have a new log containing the profile fetched from the SAML

`logApp.debug('[SAML] Successfully logged', { profile });`

It will help debug what going wrong with the roles config

```
"roles_management": {
    "role_attributes": ["Role"],
    "roles_mapping": ["ITSecOps"]
 }
```

**Comment by richard-julien** [comment]
Oh i miss that initially but your roles mapping configuration looks wrong.
It must be SAML_ROLES:OPENCTI_ROLE

So something like

```
"roles_management": {
    "role_attributes": ["Role"],
    "roles_mapping": ["ITSecOps:Administrator"]
}
```

**Comment by smclinden** [comment]
```
{"category":"APP","level":"debug","message":"[SAML] Successfully logged","profile":{"attributes":{"http://schemas.microsoft.com/claims/authnmethodsreferences":["urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport","http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/x509"],"http://schemas.microsoft.com/identity/claims/displayname":"Mclinden, Sean","http://schemas.microsoft.com/identity/claims/identityprovider":"https://sts.windows.net/xxxx/","http://schemas.microsoft.com/identity/claims/objectidentifier":"19fb9893-7ad4-4655-ae6e-91e6820dc4c1","http://schemas.microsoft.com/identity/claims/tenantid":"xxxx","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"Sean.Mclinden@xxxx.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname":"Sean","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name":"Sean.Mclinden@xxxx.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname":"Mclinden"},"http://schemas.microsoft.com/claims/authnmethodsreferences":["urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport","http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/x509"],"http://schemas.microsoft.com/identity/claims/displayname":"Mclinden, Sean","http://schemas.microsoft.com/identity/claims/identityprovider":"https://sts.windows.net/xxxx/","http://schemas.microsoft.com/identity/claims/objectidentifier":"19fb9893-7ad4-4655-ae6e-91e6820dc4c1","http://schemas.microsoft.com/identity/claims/tenantid":"xxxx","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":"Sean.Mclinden@xxxx.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname":"Sean","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name":"Sean.Mclinden@xxxx.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname":"Mclinden","inResponseTo":"_29a2f76f58bd7cb1aeb3","issuer":"https://sts.windows.net/xxxx/","nameID":"Sean.Mclinden@xxxx.com","nameIDFormat":"urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress","sessionIndex":"_95cc7fb8-43c1-4f70-af6b-3842198c3601"},"timestamp":"2023-02-06T17:56:02.059Z","version":"5.5.2"}
{"auth":{"ip":"172.31.91.166","referer":"https://login.microsoftonline.com/"},"category":"AUDIT","level":"error","message":"LOGIN","resource":{"error":"Restricted access, ask your administrator","provider":"saml"},"timestamp":"2023-02-06T17:56:02.060Z","version":"5.5.2"}
```

**Comment by smclinden** [comment]
Do you mean Azure AD "roles" or "groups" for SAML?

**Comment by richard-julien** [comment]
Looks like your profile that coming from the SAML login doesnt have any information about roles or groups for your user.
In OpenCTI you can map SAML groups into OPENCTI groups or roles depending on the configuration. In your configuration you decide to map the "Role" attribute from SAML to OpenCTI Roles but as you have no "Role" attribute in the response OpenCTI cant assign the roles and so fail with the "Restricted access, ask your administrator" error.

**Comment by smclinden** [comment]
The "roles" that are associated with SAML are for managing the configuration. For authentication we user Users and Groups. In this case, all of the OpenCTI users are in a single group.

**Comment by richard-julien** [comment]
Yeah I understand, i just tell you that you dont have any roles coming from the SAML callback.

**Comment by smclinden** [comment]
The only "roles" are builtin. "Reports Reader" and "Cloud Application Administrator". Do I need to create another?

**Comment by richard-julien** [comment]
Its depends of your needs. Can you join the slack and have a quick talk about that?

**Comment by smclinden** [comment]
Yes. If you send me an invitation. I sent the preferred email address to your corporate email.

**Comment by richard-julien** [comment]
Quick feedback after the call with @smclinden .
In the latest version there is 2 new behaviors:
- authnContext is now a List. (due to saml lib upgrade). So if you need to use it you have to change the config to give a list.
- Roles/Groups mapping are now enforced and prevent to login if the configuration is not correct.

In this case it was both. In order to make it work back, the authnContext was transform to a list and the roles_management was clear because not really needed.

Hope this thread could help some other users struggling with SAML.

**Comment by smclinden** [comment]
To add to this, if you omit the authnContext it now defaults to the SAML 2 schema:

```
["urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"]

```

Which, in most cases (including Azure) would be correct. The possble other schemas can be found, here:

https://docs.oasis-open.org/security/saml/v2.0/saml-authn-context-2.0-os.pdf
